-- Lit Ladies Book Club — Database Schema
-- Run this in the Supabase SQL editor

-- Books (read or on wishlist)
CREATE TABLE books (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  author text NOT NULL,
  author_gender text CHECK (author_gender IN ('female', 'male', 'unknown')),
  genre text,
  page_count int,
  goodreads_rating numeric(3,2),
  cover_url text,
  google_books_id text,
  created_at timestamptz DEFAULT now()
);

-- Books we've read at club
CREATE TABLE book_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid REFERENCES books(id) ON DELETE CASCADE,
  date_read date,
  meeting_date timestamptz,
  meeting_location text,
  created_at timestamptz DEFAULT now()
);

-- Member ratings per book
CREATE TABLE ratings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_log_id uuid REFERENCES book_log(id) ON DELETE CASCADE,
  member_name text NOT NULL,
  score numeric(3,1) CHECK (score >= 1 AND score <= 10),
  created_at timestamptz DEFAULT now()
);

-- Wishlist books
CREATE TABLE wishlist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid REFERENCES books(id) ON DELETE CASCADE,
  suggested_by text,
  created_at timestamptz DEFAULT now()
);

-- Votes for next book
CREATE TABLE votes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid REFERENCES books(id) ON DELETE CASCADE,
  member_name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Club members (simple list, no auth)
CREATE TABLE members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE
);

-- Discussion guides cache (generated by Claude)
CREATE TABLE discussion_guides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid REFERENCES books(id) ON DELETE CASCADE UNIQUE,
  questions jsonb NOT NULL DEFAULT '[]',
  themes jsonb NOT NULL DEFAULT '[]',
  author_note text,
  quotes_prompt text,
  created_at timestamptz DEFAULT now()
);

-- Enable Row Level Security (allow all for admin-only app)
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE book_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE discussion_guides ENABLE ROW LEVEL SECURITY;

-- Allow all operations (admin-only app, no auth)
CREATE POLICY "allow_all" ON books FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON book_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON ratings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON wishlist FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON votes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON discussion_guides FOR ALL USING (true) WITH CHECK (true);
